### ISSUE TITLE
8.10 branch doesn't build with GHC-8.10.1

### ISSUE THREAD

**Issue by phadej** [haskell/haddock#1128]
```
src/Haddock/GhcUtils.hs:41:30: error:
    Module ‘TyCoRep’ does not export ‘isRuntimeRepVar’
   |
41 | import TyCoRep   ( Type(..), isRuntimeRepVar )
```

**Comment by phadej** [comment]
```
% ghc-8.10.1 --print-project-git-commit-id
ea1581cb2fd567e9b2ab8c9628196950f50a1e7e
% ghc-8.10.1 --version                    
The Glorious Glasgow Haskell Compilation System, version 8.10.0.20200123
```

**Comment by harpocrates** [comment]
Even worse, a bunch of commits from the 8.8 branch of Haddock haven't been moved over yet.

**Comment by harpocrates** [comment]
This is fixed.
